//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

protocol ___VARIABLE_SERVICENAME___Provider {
	var ___VARIABLE_SERVICENAME___: ___VARIABLE_SERVICENAME___Protocol { get }
}

protocol ___VARIABLE_SERVICENAME___Protocol {

}

final class ___VARIABLE_SERVICENAME___: ___VARIABLE_SERVICENAME___Protocol {
	private let dependencies: ___VARIABLE_SERVICENAME___DependenciesProtocol

	init(dependencies: ___VARIABLE_SERVICENAME___DependenciesProtocol) {
		self.dependencies = dependencies
	}
}
