//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

@testable import ___PROJECTNAME___
import Nimble
import Quick
import UIKit

final class ___VARIABLE_SERVICENAME___Spec: QuickSpec {
	override func spec() {
		describe("___VARIABLE_SERVICENAME___") {
			context("when ...") {
				it("should ...") {

				}
			}
		}
	}
}
