//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

protocol ___VARIABLE_SERVICENAME___DependenciesProtocol {
	
}

struct ___VARIABLE_SERVICENAME___Dependencies: ___VARIABLE_SERVICENAME___DependenciesProtocol {
	
}
