//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Christian Elies @crelies
//

import Foundation

final class Mock___VARIABLE_SERVICENAME___: ___VARIABLE_SERVICENAME___Protocol {
	
}
